### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hanifdwyputras** [hanifdwyputras/JHSBot#1]
## TODO :heavy_check_mark: 

- [ ] Google Drive Integration
- [ ] Context (alias for baileys message instance) (ref: https://github.com/hansputera/my-whatsapp-bot/blob/dev/src/extends/context.ts)
- [ ] Message collector (ref: https://github.com/hansputera/my-whatsapp-bot/blob/dev/src/extends/collector.ts)
- [ ] Send message scheduler.
- [ ] Command handler (include arguments&mention parsing) (ref: https://github.com/hansputera/my-whatsapp-bot/blob/dev/src/listeners/messageUpsert.ts).
